---
title: "Apprenez à manier l'informatique ici !"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---

```{r, echo=FALSE}
htmltools::img(src = knitr::image_uri(file.path("C:","Users","Gigi","OneDrive - UCL","Documents","UCL","MASTER","MASTER 2","Q2","Model biologiques","github","Internet Guide","bon","Case-Telenet","images", "logo2.png")), 
               alt = 'logo', 
               width = "80",
               height = "80",
               style = 'position:absolute; top:0; right:0; padding:10px;')
```

<style type="text/css">
.title {
  display: none;
}
.list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
    background-color: orange;
}

a:link {
    color: green;
}

 a:hover {
    color: red;
}
</style>

Suivez les étapes de cette page pour accéder à ce dont vous avez besoin en quelques clics seulement. Vous pouvez changer la langue en haut de l'écran. \hfill \break Besoin d'aide ? **Appelez-nous au 015 66 66 66.** Nous sommes là pour vous ! Vous n'avez pas besoin de ce guide ? Cliquez [ici](https://www.google.com/).

# Accédez à vos mails:

1. Pour **Gmail**, cliquez sur ce lien: <https://www.google.com/intl/fr/gmail/about/>.

2. Pour **Outlook**, cliquez sur ce lien: <https://outlook.live.com/owa/>.

#### Besoin d'aide pour vous connecter ?

1. Si vous avez déjà un compte, cliquez sur **‘Sign in’**. 

2. Si vous n'avez pas encore de compte, cliquez sur **'Create an account'**.

# Access your bank account

1. Pour **Belfius**, cliquez sur ce lien: <https://www.belfius.be/common/FR/fw/language.html>.

2. Pour **BNP**, cliquez sur ce lien: <http://rmarkdown.rstudio.com>.

#### Besoin d'aide ?

Nous suggérons que vous appeliez le service client :

1. Appelez Belfius au : 02 222 12 02

2. Appelez BNP au : 00 33 1 57 08 22 00